export const selectAuth = (state) => state.auth;
export const selectCurrentUser = (state) => state.auth.user;
export const selectIsAuthenticated = (state) => state.auth.isAuthenticated;
export const selectAuthToken = (state) => state.auth.token;
export const selectAuthLoading = (state) => state.auth.loading;
export const selectAuthError = (state) => state.auth.error;
export const selectSession = (state) => state.auth.session;
export const selectSessionStatus = (state) => state.auth.sessionStatus;
export const selectTokenExpiresAt = (state) => state.auth.tokenExpiresAt;
